# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170119_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_url',
            field=models.TextField(default='https://chipinworld.com/images/product/default_product.png'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_url',
            field=models.TextField(default='https://chipinworld.com/images/product/default_product.png'),
        ),
    ]
