# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 15:59
from __future__ import unicode_literals

from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_unit_of_measure'),
    ]

    operations = [
        TrigramExtension()
    ]
